kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-access-readonly
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-user-view-access
subjects:
- kind: Group
  namespace: web
  name: 255b91c1-a17a-49a1-af41-48caba820e2d